"""
Application-wide constants for the AI Trading Agent.
"""

# Trading Actions
TRADE_ACTION_BUY = "buy"
TRADE_ACTION_SELL = "sell"
TRADE_ACTION_HOLD = "hold"

VALID_TRADE_ACTIONS = {TRADE_ACTION_BUY, TRADE_ACTION_SELL, TRADE_ACTION_HOLD}

# Trading Intervals
INTERVAL_5M = "5m"
INTERVAL_1H = "1h"
INTERVAL_4H = "4h"
INTERVAL_1D = "1d"

VALID_INTERVALS = {INTERVAL_5M, INTERVAL_1H, INTERVAL_4H, INTERVAL_1D}

# Timeframe Mappings (in minutes)
INTERVAL_TO_MINUTES = {
    INTERVAL_5M: 5,
    INTERVAL_1H: 60,
    INTERVAL_4H: 240,
    INTERVAL_1D: 1440,
}

# Order Status
ORDER_STATUS_PENDING = "pending"
ORDER_STATUS_FILLED = "filled"
ORDER_STATUS_PARTIALLY_FILLED = "partially_filled"
ORDER_STATUS_CANCELLED = "cancelled"
ORDER_STATUS_REJECTED = "rejected"

VALID_ORDER_STATUSES = {
    ORDER_STATUS_PENDING,
    ORDER_STATUS_FILLED,
    ORDER_STATUS_PARTIALLY_FILLED,
    ORDER_STATUS_CANCELLED,
    ORDER_STATUS_REJECTED,
}

# Position Status
POSITION_STATUS_OPEN = "open"
POSITION_STATUS_CLOSED = "closed"
POSITION_STATUS_LIQUIDATED = "liquidated"

VALID_POSITION_STATUSES = {
    POSITION_STATUS_OPEN,
    POSITION_STATUS_CLOSED,
    POSITION_STATUS_LIQUIDATED,
}

# Account Status
ACCOUNT_STATUS_ACTIVE = "active"
ACCOUNT_STATUS_PAUSED = "paused"
ACCOUNT_STATUS_STOPPED = "stopped"

VALID_ACCOUNT_STATUSES = {
    ACCOUNT_STATUS_ACTIVE,
    ACCOUNT_STATUS_PAUSED,
    ACCOUNT_STATUS_STOPPED,
}

# Technical Indicators
INDICATOR_EMA = "ema"
INDICATOR_MACD = "macd"
INDICATOR_RSI = "rsi"
INDICATOR_ATR = "atr"
INDICATOR_BOLLINGER_BANDS = "bollinger_bands"

# Default Technical Analysis Parameters
DEFAULT_EMA_PERIODS = [20, 50, 200]
DEFAULT_RSI_PERIOD = 14
DEFAULT_MACD_FAST = 12
DEFAULT_MACD_SLOW = 26
DEFAULT_MACD_SIGNAL = 9
DEFAULT_ATR_PERIOD = 14
DEFAULT_BOLLINGER_BANDS_PERIOD = 20
DEFAULT_BOLLINGER_BANDS_STD_DEV = 2

# Risk Management
DEFAULT_LEVERAGE = 2.0
MIN_LEVERAGE = 1.0
MAX_LEVERAGE = 5.0

DEFAULT_POSITION_SIZE_USD = 1000.0
MIN_POSITION_SIZE_USD = 100.0
MAX_POSITION_SIZE_USD = 100000.0

# Performance Metrics
SHARPE_RATIO_RISK_FREE_RATE = 0.0
SHARPE_RATIO_ANNUALIZATION_FACTOR = 252  # Trading days per year

SORTINO_RATIO_TARGET_RETURN = 0.0
SORTINO_RATIO_ANNUALIZATION_FACTOR = 252  # Trading days per year

# API Response Codes
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_SERVER_ERROR = 500
HTTP_SERVICE_UNAVAILABLE = 503

# Retry Configuration
DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_BACKOFF_FACTOR = 2
DEFAULT_RETRY_INITIAL_DELAY = 1  # seconds

# WebSocket Configuration
WEBSOCKET_HEARTBEAT_INTERVAL = 30  # seconds
WEBSOCKET_PING_INTERVAL = 30  # seconds
WEBSOCKET_PONG_TIMEOUT = 10  # seconds

# Cache Configuration
CACHE_TTL_MARKET_DATA = 60  # seconds
CACHE_TTL_ACCOUNT_STATE = 30  # seconds
CACHE_TTL_POSITIONS = 30  # seconds

# Logging
LOG_LEVEL_DEBUG = "DEBUG"
LOG_LEVEL_INFO = "INFO"
LOG_LEVEL_WARNING = "WARNING"
LOG_LEVEL_ERROR = "ERROR"
LOG_LEVEL_CRITICAL = "CRITICAL"

VALID_LOG_LEVELS = {
    LOG_LEVEL_DEBUG,
    LOG_LEVEL_INFO,
    LOG_LEVEL_WARNING,
    LOG_LEVEL_ERROR,
    LOG_LEVEL_CRITICAL,
}

# Default Assets
DEFAULT_ASSETS = ["BTC", "ETH", "SOL"]

# Supported LLM Models
SUPPORTED_LLM_MODELS = [
    "x-ai/grok-4",
    "deepseek/deepseek-chat",
    "anthropic/claude-3-sonnet",
    "openai/gpt-4",
    "openai/gpt-4-turbo",
]

# API Endpoints
API_ENDPOINT_HEALTH = "/health"
API_ENDPOINT_STATUS = "/status"
API_ENDPOINT_DIARY = "/diary"
API_ENDPOINT_LOGS = "/logs"
API_ENDPOINT_POSITIONS = "/positions"
API_ENDPOINT_PERFORMANCE = "/performance"
API_ENDPOINT_ACCOUNTS = "/accounts"

# WebSocket Endpoints
WS_ENDPOINT_TRADING_EVENTS = "/ws/trading-events"
WS_ENDPOINT_MARKET_DATA = "/ws/market-data"
WS_ENDPOINT_POSITIONS = "/ws/positions"

# Database
DATABASE_POOL_TIMEOUT = 30  # seconds
DATABASE_ECHO_POOL = False
DATABASE_POOL_PRE_PING = True

# Pagination
DEFAULT_PAGE_SIZE = 100
MAX_PAGE_SIZE = 1000

