"""initial_baseline

Revision ID: bfb15195438f
Revises:
Create Date: 2025-11-27 10:10:38.679417

Note: This migration uses DOUBLE_PRECISION for all floating-point columns
to ensure consistency with init-db.sql and provide better precision for
financial data. PostgreSQL DOUBLE PRECISION provides ~15 decimal digits
of precision vs ~6 for REAL.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import DOUBLE_PRECISION

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfb15195438f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "challenges",
        sa.Column("address", sa.String(length=42), nullable=False),
        sa.Column("challenge", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("challenge"),
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_challenges_address"),
        "challenges",
        ["address"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_challenges_id"), "challenges", ["id"], unique=False, schema="trading"
    )
    op.create_table(
        "strategies",
        sa.Column("strategy_id", sa.String(length=100), nullable=False),
        sa.Column("strategy_name", sa.String(length=255), nullable=False),
        sa.Column("strategy_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("prompt_template", sa.Text(), nullable=False),
        sa.Column("timeframe_preference", sa.JSON(), nullable=False),
        sa.Column("max_positions", sa.Integer(), nullable=False),
        sa.Column("position_sizing", sa.String(length=50), nullable=False),
        sa.Column("order_preference", sa.String(length=50), nullable=False),
        sa.Column("funding_rate_threshold", DOUBLE_PRECISION(), nullable=False),
        sa.Column("risk_parameters", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="trading",
    )
    op.create_index(
        "idx_strategy_active", "strategies", ["is_active"], unique=False, schema="trading"
    )
    op.create_index(
        "idx_strategy_id_unique", "strategies", ["strategy_id"], unique=True, schema="trading"
    )
    op.create_index(
        "idx_strategy_type", "strategies", ["strategy_type"], unique=False, schema="trading"
    )
    op.create_index(
        op.f("ix_trading_strategies_id"), "strategies", ["id"], unique=False, schema="trading"
    )
    op.create_index(
        op.f("ix_trading_strategies_strategy_id"),
        "strategies",
        ["strategy_id"],
        unique=True,
        schema="trading",
    )
    op.create_table(
        "users",
        sa.Column("address", sa.String(length=42), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_users_address"), "users", ["address"], unique=True, schema="trading"
    )
    op.create_index(op.f("ix_trading_users_id"), "users", ["id"], unique=False, schema="trading")
    op.create_table(
        "accounts",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=True),
        sa.Column("api_secret", sa.String(length=255), nullable=True),
        sa.Column("api_passphrase", sa.String(length=255), nullable=True),
        sa.Column("leverage", DOUBLE_PRECISION(), nullable=False),
        sa.Column("max_position_size_usd", DOUBLE_PRECISION(), nullable=False),
        sa.Column("risk_per_trade", DOUBLE_PRECISION(), nullable=False),
        sa.Column("maker_fee_bps", DOUBLE_PRECISION(), nullable=False),
        sa.Column("taker_fee_bps", DOUBLE_PRECISION(), nullable=False),
        sa.Column("balance_usd", DOUBLE_PRECISION(), nullable=False),
        sa.Column("is_paper_trading", sa.Boolean(), nullable=False),
        sa.Column("is_multi_account", sa.Boolean(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["trading.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_accounts_id"), "accounts", ["id"], unique=False, schema="trading"
    )
    op.create_index(
        op.f("ix_trading_accounts_name"), "accounts", ["name"], unique=True, schema="trading"
    )
    op.create_table(
        "decisions",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.String(length=100), nullable=False),
        sa.Column("asset_decisions", sa.JSON(), nullable=True),
        sa.Column("portfolio_rationale", sa.Text(), nullable=True),
        sa.Column("total_allocation_usd", DOUBLE_PRECISION(), nullable=True),
        sa.Column("portfolio_risk_level", sa.String(length=10), nullable=True),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column("action", sa.String(length=20), nullable=True),
        sa.Column("allocation_usd", DOUBLE_PRECISION(), nullable=True),
        sa.Column("tp_price", DOUBLE_PRECISION(), nullable=True),
        sa.Column("sl_price", DOUBLE_PRECISION(), nullable=True),
        sa.Column("exit_plan", sa.Text(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("confidence", DOUBLE_PRECISION(), nullable=True),
        sa.Column("risk_level", sa.String(length=10), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("position_adjustment", sa.JSON(), nullable=True),
        sa.Column("order_adjustment", sa.JSON(), nullable=True),
        sa.Column("model_used", sa.String(length=100), nullable=False),
        sa.Column("api_cost", DOUBLE_PRECISION(), nullable=True),
        sa.Column("processing_time_ms", DOUBLE_PRECISION(), nullable=False),
        sa.Column("validation_passed", sa.Boolean(), nullable=False),
        sa.Column("validation_errors", sa.JSON(), nullable=True),
        sa.Column("validation_warnings", sa.JSON(), nullable=True),
        sa.Column("market_context", sa.JSON(), nullable=False),
        sa.Column("account_context", sa.JSON(), nullable=False),
        sa.Column("risk_metrics", sa.JSON(), nullable=True),
        sa.Column("executed", sa.Boolean(), nullable=False),
        sa.Column("executed_at", sa.DateTime(), nullable=True),
        sa.Column("execution_price", DOUBLE_PRECISION(), nullable=True),
        sa.Column("execution_errors", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading.accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trading",
    )
    op.create_index(
        "idx_decision_account_symbol",
        "decisions",
        ["account_id", "symbol"],
        unique=False,
        schema="trading",
    )
    op.create_index("idx_decision_action", "decisions", ["action"], unique=False, schema="trading")
    op.create_index(
        "idx_decision_strategy", "decisions", ["strategy_id"], unique=False, schema="trading"
    )
    op.create_index(
        "idx_decision_timestamp", "decisions", ["timestamp"], unique=False, schema="trading"
    )
    op.create_index(
        op.f("ix_trading_decisions_id"), "decisions", ["id"], unique=False, schema="trading"
    )
    op.create_index(
        op.f("ix_trading_decisions_strategy_id"),
        "decisions",
        ["strategy_id"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_decisions_symbol"), "decisions", ["symbol"], unique=False, schema="trading"
    )
    op.create_table(
        "diary_entries",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("entry_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tags", sa.String(length=255), nullable=True),
        sa.Column("sentiment", sa.String(length=20), nullable=True),
        sa.Column("confidence", sa.String(length=20), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading.accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trading",
    )
    op.create_index(
        "idx_diary_account_id", "diary_entries", ["account_id"], unique=False, schema="trading"
    )
    op.create_index(
        "idx_diary_entry_type", "diary_entries", ["entry_type"], unique=False, schema="trading"
    )
    op.create_index(
        op.f("ix_trading_diary_entries_account_id"),
        "diary_entries",
        ["account_id"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_diary_entries_id"), "diary_entries", ["id"], unique=False, schema="trading"
    )
    op.create_table(
        "performance_metrics",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=50), nullable=False),
        sa.Column("period_start", sa.String(length=50), nullable=False),
        sa.Column("period_end", sa.String(length=50), nullable=False),
        sa.Column("total_trades", sa.Integer(), nullable=False),
        sa.Column("winning_trades", sa.Integer(), nullable=False),
        sa.Column("losing_trades", sa.Integer(), nullable=False),
        sa.Column("win_rate", DOUBLE_PRECISION(), nullable=False),
        sa.Column("total_pnl", DOUBLE_PRECISION(), nullable=False),
        sa.Column("total_pnl_percent", DOUBLE_PRECISION(), nullable=False),
        sa.Column("average_win", DOUBLE_PRECISION(), nullable=True),
        sa.Column("average_loss", DOUBLE_PRECISION(), nullable=True),
        sa.Column("profit_factor", DOUBLE_PRECISION(), nullable=True),
        sa.Column("max_drawdown", DOUBLE_PRECISION(), nullable=True),
        sa.Column("max_drawdown_percent", DOUBLE_PRECISION(), nullable=True),
        sa.Column("sharpe_ratio", DOUBLE_PRECISION(), nullable=True),
        sa.Column("sortino_ratio", DOUBLE_PRECISION(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading.accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trading",
    )
    op.create_index(
        "idx_performance_account_id",
        "performance_metrics",
        ["account_id"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        "idx_performance_period", "performance_metrics", ["period"], unique=False, schema="trading"
    )
    op.create_index(
        op.f("ix_trading_performance_metrics_account_id"),
        "performance_metrics",
        ["account_id"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_performance_metrics_id"),
        "performance_metrics",
        ["id"],
        unique=False,
        schema="trading",
    )
    op.create_table(
        "positions",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("entry_price", DOUBLE_PRECISION(), nullable=False),
        sa.Column("current_price", DOUBLE_PRECISION(), nullable=False),
        sa.Column("quantity", DOUBLE_PRECISION(), nullable=False),
        sa.Column("leverage", DOUBLE_PRECISION(), nullable=False),
        sa.Column("entry_value", DOUBLE_PRECISION(), nullable=False),
        sa.Column("current_value", DOUBLE_PRECISION(), nullable=False),
        sa.Column("unrealized_pnl", DOUBLE_PRECISION(), nullable=False),
        sa.Column("unrealized_pnl_percent", DOUBLE_PRECISION(), nullable=False),
        sa.Column("stop_loss", DOUBLE_PRECISION(), nullable=True),
        sa.Column("take_profit", DOUBLE_PRECISION(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading.accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trading",
    )
    op.create_index(
        "idx_position_account_id", "positions", ["account_id"], unique=False, schema="trading"
    )
    op.create_index("idx_position_status", "positions", ["status"], unique=False, schema="trading")
    op.create_index("idx_position_symbol", "positions", ["symbol"], unique=False, schema="trading")
    op.create_index(
        op.f("ix_trading_positions_account_id"),
        "positions",
        ["account_id"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_positions_id"), "positions", ["id"], unique=False, schema="trading"
    )
    op.create_table(
        "strategy_assignments",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.Column("assigned_by", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("previous_strategy_id", sa.Integer(), nullable=True),
        sa.Column("switch_reason", sa.Text(), nullable=True),
        sa.Column("total_trades", sa.Integer(), nullable=False),
        sa.Column("total_pnl", DOUBLE_PRECISION(), nullable=False),
        sa.Column("win_rate", DOUBLE_PRECISION(), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(), nullable=True),
        sa.Column("deactivated_by", sa.String(length=100), nullable=True),
        sa.Column("deactivation_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading.accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_strategy_id"],
            ["trading.strategies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["trading.strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trading",
    )
    op.create_index(
        "idx_strategy_assignment_account",
        "strategy_assignments",
        ["account_id"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        "idx_strategy_assignment_active",
        "strategy_assignments",
        ["is_active"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        "idx_strategy_assignment_strategy",
        "strategy_assignments",
        ["strategy_id"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_strategy_assignments_id"),
        "strategy_assignments",
        ["id"],
        unique=False,
        schema="trading",
    )
    op.create_table(
        "strategy_performances",
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("period_start", sa.DateTime(), nullable=False),
        sa.Column("period_end", sa.DateTime(), nullable=False),
        sa.Column("period_days", sa.Integer(), nullable=False),
        sa.Column("total_trades", sa.Integer(), nullable=False),
        sa.Column("winning_trades", sa.Integer(), nullable=False),
        sa.Column("losing_trades", sa.Integer(), nullable=False),
        sa.Column("win_rate", DOUBLE_PRECISION(), nullable=False),
        sa.Column("total_pnl", DOUBLE_PRECISION(), nullable=False),
        sa.Column("avg_win", DOUBLE_PRECISION(), nullable=False),
        sa.Column("avg_loss", DOUBLE_PRECISION(), nullable=False),
        sa.Column("max_win", DOUBLE_PRECISION(), nullable=False),
        sa.Column("max_loss", DOUBLE_PRECISION(), nullable=False),
        sa.Column("max_drawdown", DOUBLE_PRECISION(), nullable=False),
        sa.Column("sharpe_ratio", DOUBLE_PRECISION(), nullable=True),
        sa.Column("sortino_ratio", DOUBLE_PRECISION(), nullable=True),
        sa.Column("profit_factor", DOUBLE_PRECISION(), nullable=False),
        sa.Column("avg_trade_duration_hours", DOUBLE_PRECISION(), nullable=False),
        sa.Column("total_volume_traded", DOUBLE_PRECISION(), nullable=False),
        sa.Column("total_fees_paid", DOUBLE_PRECISION(), nullable=False),
        sa.Column("total_funding_paid", DOUBLE_PRECISION(), nullable=False),
        sa.Column("total_liquidations", sa.Integer(), nullable=False),
        sa.Column("var_95", DOUBLE_PRECISION(), nullable=True),
        sa.Column("max_consecutive_losses", sa.Integer(), nullable=False),
        sa.Column("max_consecutive_wins", sa.Integer(), nullable=False),
        sa.Column("additional_metrics", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading.accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["trading.strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trading",
    )
    op.create_index(
        "idx_strategy_performance_account",
        "strategy_performances",
        ["account_id"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        "idx_strategy_performance_period",
        "strategy_performances",
        ["period_start", "period_end"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        "idx_strategy_performance_strategy",
        "strategy_performances",
        ["strategy_id"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_strategy_performances_id"),
        "strategy_performances",
        ["id"],
        unique=False,
        schema="trading",
    )
    op.create_table(
        "decision_results",
        sa.Column("decision_id", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=True),
        sa.Column("realized_pnl", DOUBLE_PRECISION(), nullable=True),
        sa.Column("unrealized_pnl", DOUBLE_PRECISION(), nullable=True),
        sa.Column("percentage_return", DOUBLE_PRECISION(), nullable=True),
        sa.Column("entry_price", DOUBLE_PRECISION(), nullable=True),
        sa.Column("exit_price", DOUBLE_PRECISION(), nullable=True),
        sa.Column("position_size", DOUBLE_PRECISION(), nullable=True),
        sa.Column("opened_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("duration_hours", DOUBLE_PRECISION(), nullable=True),
        sa.Column("max_favorable_excursion", DOUBLE_PRECISION(), nullable=True),
        sa.Column("max_adverse_excursion", DOUBLE_PRECISION(), nullable=True),
        sa.Column("slippage", DOUBLE_PRECISION(), nullable=True),
        sa.Column("fees_paid", DOUBLE_PRECISION(), nullable=True),
        sa.Column("hit_tp", sa.Boolean(), nullable=True),
        sa.Column("hit_sl", sa.Boolean(), nullable=True),
        sa.Column("manual_close", sa.Boolean(), nullable=False),
        sa.Column("market_conditions", sa.JSON(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["trading.decisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trading",
    )
    op.create_index(
        "idx_decision_result_closed_at",
        "decision_results",
        ["closed_at"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        "idx_decision_result_decision",
        "decision_results",
        ["decision_id"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        "idx_decision_result_outcome",
        "decision_results",
        ["outcome"],
        unique=False,
        schema="trading",
    )
    op.create_index(
        op.f("ix_trading_decision_results_id"),
        "decision_results",
        ["id"],
        unique=False,
        schema="trading",
    )
    op.create_table(
        "orders",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=True),
        sa.Column("exchange_order_id", sa.String(length=255), nullable=True),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("order_type", sa.String(length=50), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("quantity", DOUBLE_PRECISION(), nullable=False),
        sa.Column("price", DOUBLE_PRECISION(), nullable=True),
        sa.Column("stop_price", DOUBLE_PRECISION(), nullable=True),
        sa.Column("time_in_force", sa.String(length=20), nullable=False),
        sa.Column("filled_quantity", DOUBLE_PRECISION(), nullable=False),
        sa.Column("average_price", DOUBLE_PRECISION(), nullable=True),
        sa.Column("total_cost", DOUBLE_PRECISION(), nullable=True),
        sa.Column("commission", DOUBLE_PRECISION(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading.accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["trading.positions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exchange_order_id"),
        schema="trading",
    )
    op.create_index(
        "idx_order_account_id", "orders", ["account_id"], unique=False, schema="trading"
    )
    op.create_index(
        "idx_order_position_id", "orders", ["position_id"], unique=False, schema="trading"
    )
    op.create_index("idx_order_status", "orders", ["status"], unique=False, schema="trading")
    op.create_index("idx_order_symbol", "orders", ["symbol"], unique=False, schema="trading")
    op.create_index(
        op.f("ix_trading_orders_account_id"),
        "orders",
        ["account_id"],
        unique=False,
        schema="trading",
    )
    op.create_index(op.f("ix_trading_orders_id"), "orders", ["id"], unique=False, schema="trading")
    op.create_index(
        op.f("ix_trading_orders_position_id"),
        "orders",
        ["position_id"],
        unique=False,
        schema="trading",
    )
    op.create_table(
        "trades",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("exchange_trade_id", sa.String(length=255), nullable=True),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("quantity", DOUBLE_PRECISION(), nullable=False),
        sa.Column("price", DOUBLE_PRECISION(), nullable=False),
        sa.Column("total_cost", DOUBLE_PRECISION(), nullable=False),
        sa.Column("commission", DOUBLE_PRECISION(), nullable=False),
        sa.Column("commission_asset", sa.String(length=50), nullable=True),
        sa.Column("pnl", DOUBLE_PRECISION(), nullable=True),
        sa.Column("pnl_percent", DOUBLE_PRECISION(), nullable=True),
        sa.Column("roi", DOUBLE_PRECISION(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading.accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["trading.orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["trading.positions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exchange_trade_id"),
        schema="trading",
    )
    op.create_index(
        "idx_trade_account_id", "trades", ["account_id"], unique=False, schema="trading"
    )
    op.create_index("idx_trade_order_id", "trades", ["order_id"], unique=False, schema="trading")
    op.create_index(
        "idx_trade_position_id", "trades", ["position_id"], unique=False, schema="trading"
    )
    op.create_index("idx_trade_symbol", "trades", ["symbol"], unique=False, schema="trading")
    op.create_index(
        op.f("ix_trading_trades_account_id"),
        "trades",
        ["account_id"],
        unique=False,
        schema="trading",
    )
    op.create_index(op.f("ix_trading_trades_id"), "trades", ["id"], unique=False, schema="trading")
    op.create_index(
        op.f("ix_trading_trades_order_id"), "trades", ["order_id"], unique=False, schema="trading"
    )
    op.create_index(
        op.f("ix_trading_trades_position_id"),
        "trades",
        ["position_id"],
        unique=False,
        schema="trading",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trading_trades_position_id"), table_name="trades", schema="trading")
    op.drop_index(op.f("ix_trading_trades_order_id"), table_name="trades", schema="trading")
    op.drop_index(op.f("ix_trading_trades_id"), table_name="trades", schema="trading")
    op.drop_index(op.f("ix_trading_trades_account_id"), table_name="trades", schema="trading")
    op.drop_index("idx_trade_symbol", table_name="trades", schema="trading")
    op.drop_index("idx_trade_position_id", table_name="trades", schema="trading")
    op.drop_index("idx_trade_order_id", table_name="trades", schema="trading")
    op.drop_index("idx_trade_account_id", table_name="trades", schema="trading")
    op.drop_table("trades", schema="trading")
    op.drop_index(op.f("ix_trading_orders_position_id"), table_name="orders", schema="trading")
    op.drop_index(op.f("ix_trading_orders_id"), table_name="orders", schema="trading")
    op.drop_index(op.f("ix_trading_orders_account_id"), table_name="orders", schema="trading")
    op.drop_index("idx_order_symbol", table_name="orders", schema="trading")
    op.drop_index("idx_order_status", table_name="orders", schema="trading")
    op.drop_index("idx_order_position_id", table_name="orders", schema="trading")
    op.drop_index("idx_order_account_id", table_name="orders", schema="trading")
    op.drop_table("orders", schema="trading")
    op.drop_index(
        op.f("ix_trading_decision_results_id"), table_name="decision_results", schema="trading"
    )
    op.drop_index("idx_decision_result_outcome", table_name="decision_results", schema="trading")
    op.drop_index("idx_decision_result_decision", table_name="decision_results", schema="trading")
    op.drop_index("idx_decision_result_closed_at", table_name="decision_results", schema="trading")
    op.drop_table("decision_results", schema="trading")
    op.drop_index(
        op.f("ix_trading_strategy_performances_id"),
        table_name="strategy_performances",
        schema="trading",
    )
    op.drop_index(
        "idx_strategy_performance_strategy", table_name="strategy_performances", schema="trading"
    )
    op.drop_index(
        "idx_strategy_performance_period", table_name="strategy_performances", schema="trading"
    )
    op.drop_index(
        "idx_strategy_performance_account", table_name="strategy_performances", schema="trading"
    )
    op.drop_table("strategy_performances", schema="trading")
    op.drop_index(
        op.f("ix_trading_strategy_assignments_id"),
        table_name="strategy_assignments",
        schema="trading",
    )
    op.drop_index(
        "idx_strategy_assignment_strategy", table_name="strategy_assignments", schema="trading"
    )
    op.drop_index(
        "idx_strategy_assignment_active", table_name="strategy_assignments", schema="trading"
    )
    op.drop_index(
        "idx_strategy_assignment_account", table_name="strategy_assignments", schema="trading"
    )
    op.drop_table("strategy_assignments", schema="trading")
    op.drop_index(op.f("ix_trading_positions_id"), table_name="positions", schema="trading")
    op.drop_index(op.f("ix_trading_positions_account_id"), table_name="positions", schema="trading")
    op.drop_index("idx_position_symbol", table_name="positions", schema="trading")
    op.drop_index("idx_position_status", table_name="positions", schema="trading")
    op.drop_index("idx_position_account_id", table_name="positions", schema="trading")
    op.drop_table("positions", schema="trading")
    op.drop_index(
        op.f("ix_trading_performance_metrics_id"),
        table_name="performance_metrics",
        schema="trading",
    )
    op.drop_index(
        op.f("ix_trading_performance_metrics_account_id"),
        table_name="performance_metrics",
        schema="trading",
    )
    op.drop_index("idx_performance_period", table_name="performance_metrics", schema="trading")
    op.drop_index("idx_performance_account_id", table_name="performance_metrics", schema="trading")
    op.drop_table("performance_metrics", schema="trading")
    op.drop_index(op.f("ix_trading_diary_entries_id"), table_name="diary_entries", schema="trading")
    op.drop_index(
        op.f("ix_trading_diary_entries_account_id"), table_name="diary_entries", schema="trading"
    )
    op.drop_index("idx_diary_entry_type", table_name="diary_entries", schema="trading")
    op.drop_index("idx_diary_account_id", table_name="diary_entries", schema="trading")
    op.drop_table("diary_entries", schema="trading")
    op.drop_index(op.f("ix_trading_decisions_symbol"), table_name="decisions", schema="trading")
    op.drop_index(
        op.f("ix_trading_decisions_strategy_id"), table_name="decisions", schema="trading"
    )
    op.drop_index(op.f("ix_trading_decisions_id"), table_name="decisions", schema="trading")
    op.drop_index("idx_decision_timestamp", table_name="decisions", schema="trading")
    op.drop_index("idx_decision_strategy", table_name="decisions", schema="trading")
    op.drop_index("idx_decision_action", table_name="decisions", schema="trading")
    op.drop_index("idx_decision_account_symbol", table_name="decisions", schema="trading")
    op.drop_table("decisions", schema="trading")
    op.drop_index(op.f("ix_trading_accounts_name"), table_name="accounts", schema="trading")
    op.drop_index(op.f("ix_trading_accounts_id"), table_name="accounts", schema="trading")
    op.drop_table("accounts", schema="trading")
    op.drop_index(op.f("ix_trading_users_id"), table_name="users", schema="trading")
    op.drop_index(op.f("ix_trading_users_address"), table_name="users", schema="trading")
    op.drop_table("users", schema="trading")
    op.drop_index(
        op.f("ix_trading_strategies_strategy_id"), table_name="strategies", schema="trading"
    )
    op.drop_index(op.f("ix_trading_strategies_id"), table_name="strategies", schema="trading")
    op.drop_index("idx_strategy_type", table_name="strategies", schema="trading")
    op.drop_index("idx_strategy_id_unique", table_name="strategies", schema="trading")
    op.drop_index("idx_strategy_active", table_name="strategies", schema="trading")
    op.drop_table("strategies", schema="trading")
    op.drop_index(op.f("ix_trading_challenges_id"), table_name="challenges", schema="trading")
    op.drop_index(op.f("ix_trading_challenges_address"), table_name="challenges", schema="trading")
    op.drop_table("challenges", schema="trading")
    # ### end Alembic commands ###
